lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  template_strings:
    - assets/test_data/bam_pass/*.bam
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Nour Mahfel
  description: A Nextflow pipeline for rare disease diagnostics from Oxford Nanopore
    long-read sequencing data. Includes SV, SNV, CNV, and methylation profiling.
  force: false
  is_nfcore: true
  name: longraredisease
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0
